### ISSUE TITLE
CoffeeScript source isn't in repo

### ISSUE THREAD

**Issue by pseudosavant** [iamdanfox/anno.js#42]
There is an `anno.js` file that indicates it was built by CoffeeScript but no source file can be found in the repo. Is Anno.js coded in CoffeeScript or JavaScript? I don't want to make changes to the `anno.js` file if it is an output and not the source.

**Comment by iamdanfox** [comment]
You're right it is built in CoffeeScript - the file you're after is `src/anno.litcoffee`.

The litcoffee extension stands for 'literate' coffeescript - essentially just regular coffeescript syntax, with markdown text interspersed.

If you've got changes in mind, that's the place to make them!

**Comment by pseudosavant** [comment]
Ah, so that is the source. I thought it _probably_ was but I wasn't familiar with 'literate' coffeescript variant. The markdown threw me off.

I am interested in trying to reduce payload size (minified and/or gzipped) and decrease onload performance impact.

**Comment by iamdanfox** [comment]
Awesome! I did a little bit of preliminary tinkering along those lines a couple of days ago, and included a `make gzip` command to the Makefile (it just minifies the source files and then gzips them to see how small the library is).
