### ISSUE TITLE
example file references don't exist

### ISSUE THREAD

**Issue by mwaschkowski** [iamdanfox/anno.js#46]
http://iamdanfox.github.io/anno.js/scrollintoview/jquery.scrollintoview.min.js

![image](https://cloud.githubusercontent.com/assets/1027250/4060901/bd3b6a40-2df3-11e4-86c4-11404af74fa4.png)

**Comment by iamdanfox** [comment]
The library now depends on the scrollintoview plugin using a 'require' call, so it's bundled in the final artefact:

https://github.com/iamdanfox/anno.js/blob/gh-pages/dist/anno.js#L736
